### ISSUE TITLE
不必要な関数っぽい

### ISSUE THREAD

**Issue by kazuminn** [mattn/files#3]
files.goで
これらがmain()で使われてないので、消したほうがいいのでは......

<pre>
var printLine = fmt.Println

var printPath = func(path string) {
	p, err := filepath.Abs(path)
	if err == nil {
		path = p
	}
	printLine(path)
}
</pre>

**Comment by mattn** [comment]
ありがとうございます。
https://github.com/mattn/files/commit/985f02e5ddb188c2cb6ddcc28dae77cdeffafa73
