### ISSUE TITLE
CtrlPで使用した時にountが大量発生

### ISSUE THREAD

**Issue by DeaR** [mattn/files#5]
適当にstderrをnulにリダイレクトするbatをでっち上げて、それを経由すると以下は発生しなかったので
間違いなくfilesではなくCtrlPかVim側だと思うのですがどちらか分からなかったので

```vim
" ファイル数が1000を超える適当なフォルダで
:let g:ctrlp_user_command = 'files -a -A -M 1000 %s'
:CtrlPClearCache
:CtrlP
```
`ount`って行がcacheの末尾付近にいっぱい
(stderrに出力されてる`Overflow max count`？)

Windows10(x64)
Vim 7.4.1944+kaoriya(x64)
go 1.6.2 windows/amd64

**Comment by mattn** [comment]
thank you
